name:                rofi-extras
version:             0.1.0.0
github:              "ndwarshuis/rofi-extras"
license:             BSD3
author:              "Nathan Dwarshuis"
maintainer:          "ndwar@yavin4.ch"
copyright:           "2020 Nathan Dwarshuis"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ndwarshuis/rofi-extras#readme>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6.5.0
- aeson >= 1.4.5.0
- unix-time >= 0.4.7
- unix >= 2.7.2.2
- dbus >= 1.2.7
- ordered-containers >= 0.2.2
- Clipboard >= 2.3.2.0
- mtl >= 2.2.2
- directory >= 1.3.3.0
- bytestring >= 0.10.8.2
- split >= 0.2.3.3
- containers >= 0.6.0.1
- filepath >= 1.4.2.1
- text >= 1.2.3.1
- unliftio >= 0.2.12
- unliftio-core >= 0.1.2.0
- X11 >= 1.9.1
- yaml >= 0.11.1.2
- vector >= 0.12.0.3

library:
  source-dirs: lib/
  ghc-options:
  - -Wall
  - -Werror
  - -threaded
  exposed-modules:
  - Bitwarden.Internal
  - Rofi.Command

executables:
  pinentry-rofi:
    main: pinentry-rofi.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    dependencies:
    - rofi-extras

  rofi-autorandr:
    main: rofi-autorandr.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    dependencies:
    - rofi-extras

  rofi-bw:
    main: rofi-bw.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    dependencies:
    - rofi-extras

  rofi-bt:
    main: rofi-bt.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    dependencies:
    - rofi-extras

  rofi-dev:
    main: rofi-dev.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    dependencies:
    - rofi-extras

  current-output:
    main: current-output.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    dependencies:
    - rofi-extras
